version: '3'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - /postgresqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - /redisdata:/root/redis
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres:1234@postgres:5432
    depends_on:
      - postgres
      - redis
    links:
      - redis
      - postgres
 
 
