version: '3'

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres:1234@postgres:5432
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - /postgresqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    
